asignacion_index:
    path:     /
    defaults: { _controller: "SquirrelBundle:asignacion:index" }
    methods:  GET

asignacion_show:
    path:     /{id}/show
    defaults: { _controller: "SquirrelBundle:asignacion:show" }
    methods:  GET

asignacion_new:
    path:     /new
    defaults: { _controller: "SquirrelBundle:asignacion:new" }
    methods:  [GET, POST]

asignacion_edit:
    path:     /{id}/edit
    defaults: { _controller: "SquirrelBundle:asignacion:edit" }
    methods:  [GET, POST]

asignacion_delete:
    path:     /{id}/delete
    defaults: { _controller: "SquirrelBundle:asignacion:delete" }
    methods:  DELETE
