estadoproyecto_index:
    path:     /
    defaults: { _controller: "SquirrelBundle:estadoProyecto:index" }
    methods:  GET

estadoproyecto_show:
    path:     /{id}/show
    defaults: { _controller: "SquirrelBundle:estadoProyecto:show" }
    methods:  GET

estadoproyecto_new:
    path:     /new
    defaults: { _controller: "SquirrelBundle:estadoProyecto:new" }
    methods:  [GET, POST]

estadoproyecto_edit:
    path:     /{id}/edit
    defaults: { _controller: "SquirrelBundle:estadoProyecto:edit" }
    methods:  [GET, POST]

estadoproyecto_delete:
    path:     /{id}/delete
    defaults: { _controller: "SquirrelBundle:estadoProyecto:delete" }
    methods:  DELETE
