indicador_index:
    path:     /
    defaults: { _controller: "SquirrelBundle:indicador:index" }
    methods:  GET

indicador_show:
    path:     /{id}/show
    defaults: { _controller: "SquirrelBundle:indicador:show" }
    methods:  GET

indicador_new:
    path:     /new
    defaults: { _controller: "SquirrelBundle:indicador:new" }
    methods:  [GET, POST]

indicador_edit:
    path:     /{id}/edit
    defaults: { _controller: "SquirrelBundle:indicador:edit" }
    methods:  [GET, POST]

indicador_delete:
    path:     /{id}/delete
    defaults: { _controller: "SquirrelBundle:indicador:delete" }
    methods:  DELETE
