menuitem_index:
    path:     /
    defaults: { _controller: "SquirrelBundle:menuItem:index" }
    methods:  GET

menuitem_show:
    path:     /{id}/show
    defaults: { _controller: "SquirrelBundle:menuItem:show" }
    methods:  GET

menuitem_new:
    path:     /new
    defaults: { _controller: "SquirrelBundle:menuItem:new" }
    methods:  [GET, POST]

menuitem_edit:
    path:     /{id}/edit
    defaults: { _controller: "SquirrelBundle:menuItem:edit" }
    methods:  [GET, POST]

menuitem_delete:
    path:     /{id}/delete
    defaults: { _controller: "SquirrelBundle:menuItem:delete" }
    methods:  DELETE
