objetivo_index:
    path:     /
    defaults: { _controller: "SquirrelBundle:objetivo:index" }
    methods:  GET

objetivo_show:
    path:     /{id}/show
    defaults: { _controller: "SquirrelBundle:objetivo:show" }
    methods:  GET

objetivo_new:
    path:     /new
    defaults: { _controller: "SquirrelBundle:objetivo:new" }
    methods:  [GET, POST]

objetivo_edit:
    path:     /{id}/edit
    defaults: { _controller: "SquirrelBundle:objetivo:edit" }
    methods:  [GET, POST]

objetivo_delete:
    path:     /{id}/delete
    defaults: { _controller: "SquirrelBundle:objetivo:delete" }
    methods:  DELETE
