proyecto_index:
    path:     /
    defaults: { _controller: "SquirrelBundle:proyecto:index" }
    methods:  GET

proyecto_show:
    path:     /{id}/show
    defaults: { _controller: "SquirrelBundle:proyecto:show" }
    methods:  GET

proyecto_new:
    path:     /new
    defaults: { _controller: "SquirrelBundle:proyecto:new" }
    methods:  [GET, POST]

proyecto_edit:
    path:     /{id}/edit
    defaults: { _controller: "SquirrelBundle:proyecto:edit" }
    methods:  [GET, POST]

proyecto_delete:
    path:     /{id}/delete
    defaults: { _controller: "SquirrelBundle:proyecto:delete" }
    methods:  DELETE
