usuario_index:
    path:     /
    defaults: { _controller: "SquirrelBundle:Usuario:index" }
    methods:  GET

usuario_show:
    path:     /{id}/show
    defaults: { _controller: "SquirrelBundle:Usuario:show" }
    methods:  GET

usuario_new:
    path:     /new
    defaults: { _controller: "SquirrelBundle:Usuario:new" }
    methods:  [GET, POST]

usuario_edit:
    path:     /{id}/edit
    defaults: { _controller: "SquirrelBundle:Usuario:edit" }
    methods:  [GET, POST]

usuario_delete:
    path:     /{id}/delete
    defaults: { _controller: "SquirrelBundle:Usuario:delete" }
    methods:  DELETE
