<?php

namespace SquirrelBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * categoriaProyectoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class categoriaProyectoRepository extends EntityRepository
{
}
