<?php

namespace SquirrelBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * necesitaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class necesitaRepository extends EntityRepository
{
}
