<?php

namespace SquirrelBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * permisoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class permisoRepository extends EntityRepository
{
}
