<?php

namespace SquirrelBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * resultadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class resultadoRepository extends EntityRepository
{
}
