<?php

namespace SquirrelBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * rolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class rolRepository extends EntityRepository
{
}
